use iced_fonts::bootstrap::Bootstrap;

use crate::theme;
use crate::types::ModuleInfo;

pub fn default_module_list() -> Vec<ModuleInfo> {
    vec![
        ModuleInfo {
            id: "always-on-top".into(),
            name: "Always on Top".into(),
            description: "Pin any window above all others".into(),
            icon: Bootstrap::PinAngle,
            accent: theme::blue(),
            hotkey: Some("Super+T".into()),
            running: false,
        },
        ModuleInfo {
            id: "awake".into(),
            name: "Awake".into(),
            description: "Prevent screen sleep and suspend".into(),
            icon: Bootstrap::CupHot,
            accent: theme::mauve(),
            hotkey: None,
            running: false,
        },
        ModuleInfo {
            id: "paste-plain".into(),
            name: "Paste as Plain Text".into(),
            description: "Paste clipboard without formatting".into(),
            icon: Bootstrap::ClipboardCheck,
            accent: theme::green(),
            hotkey: Some("Super+Ctrl+V".into()),
            running: false,
        },
        ModuleInfo {
            id: "color-picker".into(),
            name: "Color Picker".into(),
            description: "Pick any colour from the screen (HEX, RGB, HSL)".into(),
            icon: Bootstrap::Droplet,
            accent: theme::teal(),
            hotkey: Some("Super+Shift+C".into()),
            running: false,
        },
        ModuleInfo {
            id: "light-switch".into(),
            name: "Light Switch".into(),
            description: "Switch between light and dark mode on a schedule".into(),
            icon: Bootstrap::BrightnessHighFill,
            accent: theme::yellow(),
            hotkey: Some("Super+Shift+D".into()),
            running: false,
        },
        ModuleInfo {
            id: "hosts-editor".into(),
            name: "Hosts Editor".into(),
            description: "GUI editor for /etc/hosts with toggle on/off".into(),
            icon: Bootstrap::FileTextFill,
            accent: theme::peach(),
            hotkey: None,
            running: false,
        },
        ModuleInfo {
            id: "bulk-rename".into(),
            name: "Bulk Rename".into(),
            description: "Batch rename files with regex and preview".into(),
            icon: Bootstrap::Pencil,
            accent: theme::pink(),
            hotkey: None,
            running: false,
        },
        ModuleInfo {
            id: "image-resizer".into(),
            name: "Image Resizer".into(),
            description: "Batch resize images with presets or custom size".into(),
            icon: Bootstrap::Images,
            accent: theme::sapphire(),
            hotkey: None,
            running: false,
        },
        ModuleInfo {
            id: "key-manager".into(),
            name: "Key Manager".into(),
            description: "Remap keys, create shortcuts, per-app rules".into(),
            icon: Bootstrap::Keyboard,
            accent: theme::lavender(),
            hotkey: None,
            running: false,
        },
        ModuleInfo {
            id: "mouse-utils".into(),
            name: "Mouse Utilities".into(),
            description: "Find My Mouse, highlighter, crosshairs, jump, wrap, gliding cursor"
                .into(),
            icon: Bootstrap::Mouse,
            accent: theme::yellow(),
            hotkey: None,
            running: false,
        },
        ModuleInfo {
            id: "screen-ruler".into(),
            name: "Screen Ruler".into(),
            description: "Measure pixels on screen".into(),
            icon: Bootstrap::Rulers,
            accent: theme::flamingo(),
            hotkey: Some("Super+Shift+R".into()),
            running: false,
        },
        ModuleInfo {
            id: "text-extractor".into(),
            name: "Text Extractor".into(),
            description: "OCR: extract text from any screen region".into(),
            icon: Bootstrap::Fonts,
            accent: theme::sky(),
            hotkey: Some("Super+Shift+T".into()),
            running: false,
        },
        ModuleInfo {
            id: "shortcut-guide".into(),
            name: "Shortcut Guide".into(),
            description: "Overlay showing available keyboard shortcuts".into(),
            icon: Bootstrap::Lightning,
            accent: theme::yellow(),
            hotkey: Some("Hold Super".into()),
            running: false,
        },
        ModuleInfo {
            id: "app-launcher".into(),
            name: "App Launcher".into(),
            description: "Quick app launcher with search and calculator".into(),
            icon: Bootstrap::Search,
            accent: theme::rosewater(),
            hotkey: None,
            running: false,
        },
        ModuleInfo {
            id: "fancy-zones".into(),
            name: "FancyZones".into(),
            description: "Advanced window tiling with custom zone layouts".into(),
            icon: Bootstrap::Grid,
            accent: theme::blue(),
            hotkey: Some("Super+Shift+Z".into()),
            running: false,
        },
        ModuleInfo {
            id: "peek".into(),
            name: "Peek".into(),
            description: "Quick file preview (images, text, PDF, media)".into(),
            icon: Bootstrap::Eye,
            accent: theme::maroon(),
            hotkey: Some("Ctrl+Space".into()),
            running: false,
        },
        ModuleInfo {
            id: "workspaces".into(),
            name: "Workspaces".into(),
            description: "Save and restore desktop app layouts".into(),
            icon: Bootstrap::WindowStack,
            accent: theme::mauve(),
            hotkey: Some("Super+Ctrl+W".into()),
            running: false,
        },
        ModuleInfo {
            id: "command-palette".into(),
            name: "Command Palette".into(),
            description: "Spotlight-like search: apps, calculator, web, commands".into(),
            icon: Bootstrap::Terminal,
            accent: theme::lavender(),
            hotkey: Some("Alt+Space".into()),
            running: false,
        },
    ]
}
