[package]
name = "mpt-color-picker"
description = "Pick any color from the screen and copy it to clipboard"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mpt-color-picker"
path = "src/main.rs"
required-features = ["gui"]

[features]
default = ["gui"]
gui = ["dep:egui", "dep:eframe", "dep:scopeguard", "mpt-common/gui"]

[dependencies]
mpt-common = { path = "../common" }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
image = "0.25"
egui = { workspace = true, optional = true }
eframe = { workspace = true, optional = true }
scopeguard = { version = "1", optional = true }
