[package]
name = "mpt-mouse-utils"
description = "Mouse utilities: find my mouse spotlight, click highlighter, crosshair"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mpt-common = { path = "../common" }
anyhow = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
